#!/bin/sh

### BEGIN INIT INFO
# Provides:          spark-master
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start Spark master daemon
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/spark/sbin:/usr/local/spark/bin

USER=spark

# clear conflicting settings from the environment
unset TMPDIR

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting the Spark master daemon" "spark-master"
                if [ ! -d /var/log/spark ]; then mkdir /var/log/spark; fi
                chown -R spark:spark /var/log/spark
                su -c /usr/local/spark/sbin/start-master.sh - $USER

		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping the Spark master daemon" "spark-master"
                su -c /usr/local/spark/sbin/stop-master.sh - $USER
		log_end_msg $?
		;;

	restart|force-reload)
		$0 stop && sleep 2 && $0 start
		;;

	*)
		echo "Usage: /etc/init.d/spark-master {start|stop|restart|force-reload}"
		exit 1
		;;
esac
