#!/bin/sh

### BEGIN INIT INFO
# Provides:          spark-slave
# Required-Start:    $remote_fs $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start Spark slave daemon
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/spark/sbin:/usr/local/spark/bin

USER=spark

# clear conflicting settings from the environment
unset TMPDIR

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting the Spark slave daemon" "spark-slave"
                if [ ! -d /var/log/spark ]; then mkdir /var/log/spark; chown spark:spark /var/log/spark; fi
                su -c /usr/local/spark/sbin/start-slave.sh - $USER

		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping the Spark slave daemon" "spark-slave"
                su -c /usr/local/spark/sbin/stop-slave.sh - $USER
		log_end_msg $?
		;;

	restart|force-reload)
		$0 stop && sleep 5 && $0 start
		;;

	*)
		echo "Usage: /etc/init.d/spark-slave {start|stop|restart|force-reload}"
		exit 1
		;;
esac
