---
  
- hosts: piSparkCluster
  remote_user: root
  tasks:
    - name: remove jdk
      apt: name=openjdk-7-jre-headless state=absent purge=yes
      environment:
        PATH: /usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin

