---
  
- hosts: piSparkCluster
  remote_user: root
  tasks:
    - name: Set http proxy for apt
      lineinfile: dest=/etc/ssh/sshrc state=absent 'line=export http_proxy="http://{{ ansible_host }}:{{ proxy_port }}"'
