---

- name: Remove previous ssh key
  file: path=/tmp/ansibKey state=absent
- file: path=/tmp/ansibKey.pub state=absent

- name: Generate ssh key for ambari usage
  command: /usr/bin/ssh-keygen -N "" -C ambari@{{ managementContainerName }} -f /tmp/ansibKey

- name: Create a started Ubuntu 14.04 container
  lxc_container:
    name: "{{ managementContainerName }}"
    container_log: true
    container_log_level: DEBUG
    template: ubuntu
    state: started
    template_options: --release trusty --packages python,openssl --auth-key /tmp/ansibKey.pub
    container_config:
        - "lxc.network.type=veth"
        - "lxc.network.link={{ lxcBridge }}"
        - "lxc.network.flags=up"
        - "lxc.network.hwaddr=00:16:3e:xx:xx:xx"
        - "lxc.cgroup.memory.limit_in_bytes=2G"

- name: Wait for container to be running…
  pause: seconds=200

- name: Install jdk in started container
  lxc_container:
    name: "{{ managementContainerName }}"
    container_command: |
        apt-get update 
        apt-get install -y openjdk-7-jdk 

- name: move ssh key to root homedir
  lxc_container:
    name: "{{ managementContainerName }}"
    container_command: |
        mkdir /root/.ssh
        mv /home/ubuntu/.ssh/authorized_keys /root/.ssh/authorized_keys
